pipeline {
    agent {
        label 'Devserver'
    }

    parameters {
        choice(name: 'select_env', choices: ['dev', 'prod'], description: 'Select environment')
    }

    options {
        skipStagesAfterUnstable()
    }

    tools {
        maven 'mymaven'
    }

    environment {
        Name = "Guhan"
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package'
                echo "hello $Name"
            }
        }

        stage('Test') {
            parallel {
                stage('testA') {
                    agent { label 'Devserver' }
                    steps {
                        echo "this is test A"
                        sh "mvn test"
                    }
                }

                stage('testB') {
                    agent { label 'Devserver' }
                    steps {
                        echo "this is test B"
                        sh "mvn test"
                    }
                }
            }

            post {
                success {
                    dir("test-pipeline/target/") {
                        stash name: "maven-build", includes: "*.jar"
                    }
                }
            }
        }

        stage('Deploy') {
            when {
                expression { params.select_env == 'dev' }
                beforeAgent true
            }
            agent { label 'Devserver' }
            steps {
                dir("/var/www/html") {
                    unstash "maven-build"
                    sh """
                        jar -xvf my-app-1.0-SNAPSHOT.jar
                    """
                }
            }
        }
    }
}
