pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                echo "this is build stage"
            }
        }
        stage('Test') {
            steps {
                echo "this is a test stage"
            }
        }
        stage('Deliver') { 
            steps {
               echo "this is deliver stage"
            }
        }
    }
}
